config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'home/index'
  # Defines the root path route ("/")

  resources :admins, only: %i[ show_teacher show_user ] do
    get 'show_teacher', on: :collection
    get 'show_user', on: :collection
  end
  # resources :admin, only: %i[teacher]

  namespace :api do
    namespace :v1 do
      resources :admins, only: %i[ index ] do
      end

      resources :teachers, only: %i[ index create show update ] do
      end

      resources :users, only: %i[ index create show update ] do
      end
    end
  end

  root to: 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  scope :teacher_time, ->() { Teacher.includes(:teacher_time_slots) }
  # Ex:- scope :active, lambda {where(:active => true)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :teacher_time_slots, dependent: :destroy
  has_one :teacher_profile, dependent: :destroy
  has_many :user_time_slots, dependent: :destroy

  accepts_nested_attributes_for :teacher_profile

  protected

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/models/teacher_profile.rb
class TeacherProfile < ApplicationRecord
  belongs_to :teacher
  has_one_attached :avatar
  has_one_attached :driving_licence
end

app/models/teacher_time_slot.rb
class TeacherTimeSlot < ApplicationRecord
  belongs_to :teacher
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_time_slots, dependent: :destroy

  protected

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/models/user_time_slot.rb
class UserTimeSlot < ApplicationRecord
  belongs_to :user
  belongs_to :teacher
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show_teacher
    @teacher = Admins::ShowTeachers.call

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  def show_user
    @users = Admins::ShowUsers.call

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @users }
    end
  end
end

app/controllers/api/v1/admins_controller.rb
module Api
  module V1
    class AdminsController < ApplicationController
      def index
        @users = User.all
        render json: @users
      end
    end
  end
end

app/controllers/api/v1/teachers_controller.rb
module Api
  module V1
    class TeachersController < ApplicationController
      include ActiveModel::Serialization

      skip_before_action :verify_authenticity_token

      before_action :find_teacher, only: %i[ show update ]

      def index
        @teachers = Teacher.includes(:teacher_profile)
        render json: @teachers, each_serializer: TeacherSerializer
      end

      def create
        @teacher = Teachers::CreateTeacherService.call(teacher_params)

        render json: { status: 'SUCCESS', message: 'teacher was created successfully!', data: @teacher }, status: :created
      rescue ActionDispatch::Http::Parameters::ParseError, RuntimeError => e
        render json: { message: e.message }
      end

      def show
        render json: @teacher, serializer: TeacherSerializer
      end

      def update
        @teacher = Teachers::UpdateTeacherService.call(@teacher, params)

        render json: @teacher, serializer: TeacherSerializer
      end

      private

      def teacher_params
        params.require(:teacher).permit(:id, :first_name, :last_name, :middle_name,
                                        :email, :phone_number, :date_of_birthday, :role, teacher_profile_attributes: {})
      end

      def find_teacher
        @teacher = Teacher.find(params[:id])
      rescue ActiveRecord::RecordNotFound,
             ActionDispatch::Http::Parameters::ParseError => e
        render json: { message: e.message }
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      include ActiveModel::Serialization

      skip_before_action :verify_authenticity_token

      before_action :find_user, only: %i[ show update ]

      def index
        @users = User.includes(:user_time_slots)
        render json: @users, each_serializer: UserSerializer
      end

      def create
        @user = Users::CreateUserService.call(user_params)

        render json: { status: 'SUCCESS', message: 'user was created successfully!', data: @user }, status: :created
      rescue ActionDispatch::Http::Parameters::ParseError, RuntimeError => e
        render json: { message: e.message }
      end

      def show
        render json: @user, serializer: UserSerializer
      end

      def update
        @user = Users::UpdateUserService.call(@user, params)

        render json: @user, serializer: UserSerializer
      end

      private

      def user_params
        params.require(:user).permit(:id, :first_name, :last_name, :middle_name,
                                     :email, :phone_number, :role)
      end

      def find_user
        @user = User.find(params[:id])
      rescue ActiveRecord::RecordNotFound,
             ActionDispatch::Http::Parameters::ParseError => e
        render json: { message: e.message }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception, if: Proc.new { |c| c.request.format != 'application/json' }
    protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="table table-hover">
  <table class="table">
   <h1>Tickets</h1>
    <thead class="table table-striped">
      <tr>
        <th scope="col">user_id</th><br>
        <th scope="col">first_name</th><br>
        <th scope="col">last_name</th>
        <th scope="col">phone_number</th><br/>
        <th scope="col">email</th>
      </tr>
    </thead>

    <tbody class="table table-striped">
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.phone_number %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/index.html.erb
<div class="table table-hover">
  <table class="table">
   <h1>Users</h1>
    <thead class="table table-striped">
      <tr>
        <th scope="col">user_id</th><br>
        <th scope="col">first_name</th><br>
        <th scope="col">last_name</th>
        <th scope="col">phone_number</th><br/>
        <th scope="col">email</th>
      </tr>
    </thead>

    <tbody class="table table-striped">
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.phone_number %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/show_teacher.html.erb
<div class="container">
  <div class="table table-bordered">
    <table class="table">
    <h1 class='text-center'>Teachers</h1>
      <thead class="table table-striped">
        <tr>
          <th scope="col">teacher_id</th><br>
          <th scope="col">first_name</th><br>
          <th scope="col">last_name</th>
          <th scope="col">phone_number</th><br/>
          <th scope="col">email</th>
          <th scope="col">costs</th>
        </tr>
      </thead>

      <tbody class="table table-striped">
        <% @teacher.each do |teacher| %>
          <tr>
            <td><%= teacher.id %></td>
            <td><%= teacher.first_name %></td>
            <td><%= teacher.last_name %></td>
            <td><%= teacher.phone_number %></td>
            <td><%= teacher.email %></td>
            <td><%= teacher.teacher_profile.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/show_user.html.erb
<div class="container">
  <div class="table table-bordered">
    <table class="table">
    <h1 class='text-center'>Users</h1>
      <thead class="table table-striped">
        <tr>
          <th scope="col">user_id</th><br>
          <th scope="col">first_name</th><br>
          <th scope="col">last_name</th>
          <th scope="col">phone_number</th><br/>
          <th scope="col">email</th>
        </tr>
      </thead>
      <tbody class="table table-striped">
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.phone_number %></td>
            <td><%= user.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<body>
<div class="container">
<main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
      <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">Design</strong>
          <h3 class="mb-0">Post title</h3>
          <div class="mb-1 text-muted">Nov 11</div>
          <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

        </div>
      </div>
    </div>
  </div>

  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        From the Firehose
      </h3>

      <article class="blog-post">
        <h2 class="blog-post-title">Sample blog post</h2>
        <p class="blog-post-meta">January 1, 2021 by <a href="#">Mark</a></p>

        <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, lists, tables, images, code, and more are all supported as expected.</p>
        <hr>
        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <h2>Blockquotes</h2>
        <p>This is an example blockquote in action:</p>
        <blockquote class="blockquote">
          <p>Quoted text goes here.</p>
        </blockquote>
        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <h3>Example lists</h3>
        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout. This is an example unordered list:</p>
        <ul>
          <li>First list item</li>
          <li>Second list item with a longer description</li>
          <li>Third list item to close it out</li>
        </ul>
        <p>And this is an ordered list:</p>
        <ol>
          <li>First list item</li>
          <li>Second list item with a longer description</li>
          <li>Third list item to close it out</li>
        </ol>
        <p>And this is a definiton list:</p>
        <dl>
          <dt>HyperText Markup Language (HTML)</dt>
          <dd>The language used to describe and define the content of a Web page</dd>
          <dt>Cascading Style Sheets (CSS)</dt>
          <dd>Used to describe the appearance of Web content</dd>
          <dt>JavaScript (JS)</dt>
          <dd>The programming language used to build advanced Web sites and applications</dd>
        </dl>
        <h2>Inline HTML elements</h2>
        <p>HTML defines a long list of available inline tags, a complete list of which can be found on the <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element">Mozilla Developer Network</a>.</p>
        <ul>
          <li><strong>To bold text</strong>, use <code class="language-plaintext highlighter-rouge">&lt;strong&gt;</code>.</li>
          <li><em>To italicize text</em>, use <code class="language-plaintext highlighter-rouge">&lt;em&gt;</code>.</li>
          <li>Abbreviations, like <abbr title="HyperText Markup Langage">HTML</abbr> should use <code class="language-plaintext highlighter-rouge">&lt;abbr&gt;</code>, with an optional <code class="language-plaintext highlighter-rouge">title</code> attribute for the full phrase.</li>
          <li>Citations, like <cite>— Mark Otto</cite>, should use <code class="language-plaintext highlighter-rouge">&lt;cite&gt;</code>.</li>
          <li><del>Deleted</del> text should use <code class="language-plaintext highlighter-rouge">&lt;del&gt;</code> and <ins>inserted</ins> text should use <code class="language-plaintext highlighter-rouge">&lt;ins&gt;</code>.</li>
          <li>Superscript <sup>text</sup> uses <code class="language-plaintext highlighter-rouge">&lt;sup&gt;</code> and subscript <sub>text</sub> uses <code class="language-plaintext highlighter-rouge">&lt;sub&gt;</code>.</li>
        </ul>
        <p>Most of these elements are styled by browsers with few modifications on our part.</p>
        <h2>Heading</h2>
        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <h3>Sub-heading</h3>
        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <pre><code>Example code block</code></pre>
        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>
      </article>

      <article class="blog-post">
        <h2 class="blog-post-title">Another blog post</h2>
        <p class="blog-post-meta">December 23, 2020 by <a href="#">Jacob</a></p>

        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <blockquote>
          <p>Longer quote goes here, maybe with some <strong>emphasized text</strong> in the middle of it.</p>
        </blockquote>
        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <h3>Example table</h3>
        <p>And don't forget about tables in these posts:</p>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Upvotes</th>
              <th>Downvotes</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Alice</td>
              <td>10</td>
              <td>11</td>
            </tr>
            <tr>
              <td>Bob</td>
              <td>4</td>
              <td>3</td>
            </tr>
            <tr>
              <td>Charlie</td>
              <td>7</td>
              <td>9</td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td>Totals</td>
              <td>21</td>
              <td>23</td>
            </tr>
          </tfoot>
        </table>

        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>
      </article>

      <article class="blog-post">
        <h2 class="blog-post-title">New feature</h2>
        <p class="blog-post-meta">December 14, 2020 by <a href="#">Chris</a></p>

        <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
        <ul>
          <li>First list item</li>
          <li>Second list item with a longer description</li>
          <li>Third list item to close it out</li>
        </ul>
        <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>
      </article>

      <nav class="blog-pagination" aria-label="Pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
      </nav>

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>

</main>

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>





</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrivingApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body >
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Ccdsgadfgvdfompany, Inc</span>
    </div>

    <ul class="list-unstyled d-flex">
    <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg>icon insogramm</a></li>
    <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg>icon telegramm</a></li>
    <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg>icon viber</a></li>
  </ul>
  </footer>

app/views/shared/_header.html.erb
<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li class="nav-link px-2 link-dark"><%= link_to 'Users', show_user_admins_path %></li>
          <li class="nav-link px-2 link-dark"><%= link_to 'Teachers', show_teacher_admins_path %></li>
          <li class="nav-link px-2 link-dark"><%= link_to 'Home', root_path %></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>